// src/components/ui/text.tsx
import { type VariantProps, cva } from "class-variance-authority";
import React from "react";

import { cn } from "@/lib/utils";

const headingVariants = cva("scroll-m-20 font-bold tracking-tight", {
  variants: {
    variant: {
      h1: "text-4xl",
      h2: "text-2xl",
      h3: "text-lg",
      h4: "text-base font-semibold",
    },
  },
});

export interface HeadingProps
  extends React.HTMLAttributes<HTMLParagraphElement>,
    VariantProps<typeof headingVariants> {}

const Heading = React.forwardRef<HTMLParagraphElement, HeadingProps>(
  ({ className, variant = "h1", ...props }, ref) => {
    const Comp = variant!;

    return <Comp className={cn(headingVariants({ variant, className }))} {...props} ref={ref} />;
  }
);

Heading.displayName = "Heading";

const Paragraph = React.forwardRef<
  HTMLParagraphElement,
  React.HTMLAttributes<HTMLParagraphElement>
>(({ className, ...props }, ref) => {
  return <p className={cn("tracking-tight", className)} {...props} ref={ref} />;
});

Paragraph.displayName = "Paragraph";

export { Heading, Paragraph };

// src/lib/components/text.svelte
<script lang="ts">
  import { cva, type VariantProps } from "class-variance-authority";
  import type { HTMLButtonAttributes } from "svelte/elements";

  const textVariants = cva("", {
    variants: {
      variant: {
        h1: "scroll-m-20 text-3xl tracking-tight lg:text-4xl",
        h2: "scroll-m-20 text-2xl tracking-tight first:mt-0",
        h3: "scroll-m-20 text-lg tracking-tight",
        p: "leading-7",
        em: "",
      },
      label: {
        true: "text-muted-foreground",
      },
      serif: {
        true: "font-serif italic",
      },
    },
  });

  interface $$Props extends HTMLButtonAttributes, VariantProps<typeof textVariants> {
    label?: boolean;
  }

  export let variant: $$Props["variant"] = "p";
  export let label: $$Props["label"] = false;
</script>

<svelte:element
  this={variant}
  class={textVariants({ variant, label, serif: $$props.serif, class: $$props.class })}
>
  <slot />
</svelte:element>
